spring:
  application:
    name: identity-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

security:
  jwt:
    secret-key: ${JWT_SECRET}
    access-expiration: 900000
    refresh-expiration: 604800000

rabbitmq:
  exchange: identity.exchange

  queue:
    candidate: candidate.queue
    employer: employer.queue

  routing-key:
    candidate-created: candidate.created
    employer-created: employer.created

server:
  forward-headers-strategy: framework