spring:
  application:
    name: identity-service

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: nexthire
    password: nexthire
    virtual-host: /

security:
  jwt:
    secret-key: ${JWT_SECRET}
    access-expiration: 900000
    refresh-expiration: 604800000

rabbitmq:
  exchange: identity.exchange

  queue:
    notification-email: notification.email.queue

    candidate: candidate.queue
    candidate-created-success: candidate.created.success
    candidate-dlq: candidate.created.failed

    employer: employer.queue
    employer-dlq: employer.created.failed
    employer-created-success: employer.created.success

  routing-key:
    notification-email: notification.email.send

    candidate-created: candidate.created
    candidate-created-success: candidate.created.success
    candidate-dlq: candidate.created.failed

    employer-created: employer.created
    employer-dlq: employer.created.failed
    employer-created-success: employer.created.success

server:
  forward-headers-strategy: framework

client:
  url: ${CLIENT_URL}