FROM python:3.11-slim

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--reload", "--reload-dir", "/usr/src/app", "--reload-include", "*.py", "--host", "0.0.0.0", "--port", "8000"]