from fastapi import APIRouter, HTTPException
from app.services.llm_service import ask_ai
from pydantic import BaseModel

router = APIRouter()


class AIRequest(BaseModel):
    """
    Input model for AI requests.

    Attributes:
        message (str): The message content to be sent to the AI.
    """

    message: str


class AIRESPONSE(BaseModel):
    """
    Pydantic model representing the AI assistant's response.

    Attributes:
        response (str): The text reply generated by the AI.
    """

    response: str


@router.post("/ask", response_model=AIRESPONSE)
def chat_ai(request: AIRequest) -> AIRESPONSE:
    """
    Send a user message to the AI assistant and get a response.

    This endpoint forwards the input message to the `ask_ai` service,
    which handles:
        - Filtering out non-work-related queries
        - Classifying user intent
        - Generating a professional AI response

    Args:
        message (str): The user input message to be processed.

    Returns:
        AIRESPONSE: A Pydantic model containing:
            - response (str): The AI-generated reply as plain text.

    Raises:
        HTTPException: Returns status code 500 if any unexpected
        error occurs during processing.

    Notes:
        - Designed for integration in a job/career platform.
        - All responses are concise and work/career-related.
        - Non-work-related queries are politely refused by the service.
    """

    if not request.message.strip():
        raise HTTPException(
            status_code=400,
            detail="The 'message' field is required and cannot be empty.",
        )

    try:
        response = ask_ai(request.message)
        return AIRESPONSE(response=response)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e)) from e
